spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true&seUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Moscow
    username: root
    password: Agni123$
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

